### ISSUE TITLE
How does every tag-sub-view remember its scrollY?

### ISSUE THREAD

**Issue by Huxpro** [Thinkmill/reacteu-app#2]
This app is really awesome.

I noticed that every time `Tabs-Navigator` be changed, the corresponding sub-view in `ViewManger` would be updated, which did not use the css `display: none` ways like ionic. But in more React ways: totally remove the prev one from the real DOM and add one activated. 

It seems does the same with "touchstone.js". But, in this app, the scrolling state (scrollY) of every sub-view can be remembered! I mean, last time you scroll to 50px, you just switch to other tag and back, it still in 50px scroll. I don't know how to do it with vanilla touchstone.js, nor in vanilla React code.

I also noticed that you do scroll in `webkit-overflow-scrolling: touch`, not ionic fake-scroller way (like iScroll). So I really wonder how you cache the scrolling state. may be in virtual DOM? how?

Final words, you guys does really awesome jobs, can not wait to try your UI framework replace Ionic.

**Comment by jossmac** [comment]
Hi @Huxpro thanks for the nice words!

We created [react-container](https://github.com/JedWatson/react-container) to remember scroll position. It's also used for `flex` style element layout in your view.

Expose `initScrollable` on the container to remember the scroll position. Used like:
- `import Container from 'react-container'`
- `const scrollPosition = Container.initScrollable()`
- `<Container scrollable={scrollPosition} />`

**Comment by JedWatson** [comment]
Thanks @Huxpro, great feedback to hear. Joss's solution is how we do it, so I'll close this. If you search the codebase for `Container.initScrollable` you'll see where it's implemented.
